---
title: "HMSC: Check convergence"
output:
  github_document:
    toc: yes
    toc_depth: 2
    fig_width: 7
    fig_height: 5
    dev: svg
    keep_html: yes
    html_preview: yes
---

In this notebook we:

2. Check and plot model fits for convergence.
3. Compute and extract the model fits to data (how well does model represent data?)
4. Plot resulting model fits

# LIBRARIES
```{r eval=TRUE, include=FALSE}
library(here)
library(tidyverse)
library(ape)
library(Hmsc)
library(ggforce)
library(rcartocolor)

source(here::here("bin", "hmsc_funs.R"))
```

# NAMES OF THE MODELS
```{r}
mynames <- vector(mode="character", length=12)

w <- 1

for (n in c(100, 1000)) {
  for (p in c("sort", "qeq")) {
    for (d in c("ma", "mp")) {
      for (m in c("full", "envi", "time")) {
         mynames[w] <- paste0(p,"_",d,"_",m,"_thin_",n,"_samples_250_chains_4.rds")
         w <- w + 1
      }
    }
  }
}
```


# MODEL CONVERGENCE
Check and plot model fits for convergence. The Gelman/Rubin's diagnostic should be 1, ideally less than 1.05.
```{r}
mybetas <- map_dfr(mynames, psrf_ess, "beta")
mygammas <- map_dfr(mynames, psrf_ess, "gamma")
myomegas <- map_dfr(mynames, psrf_ess, "omega")
myrhos <- map_dfr(mynames, psrf_ess, "rho")
```

```{r}
p <- ggplot(myrhos) +
  geom_freqpoly(aes(x=ess, color=interaction(distribution, thin)), bins=50) +
  facet_grid(model~phase, scales="free") +
  labs(x="Model Specification", y="Gelman and Rubin's convergence diagnostic") +
  scale_color_carto_d(palette="Vivid") +
  theme_bw() +
  theme(axis.text.x=element_text(angle = -90, vjust = 0.5)) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())

ggsave(here::here("figs", "mcmc_convergence", "ESS_rho.svg"), plot=p, device="svg",
                  units="cm", width=17.8, height=17.8)

p
```


```{r}
mybetas %>%
  group_by(model, thin) %>%
  summarize(p.est.m=mean(p.est, na.rm=T),
            p.est.sd=sd(p.est, na.rm=T)) %>%
  write_tsv(here::here("tables", "mcmc_convergence", "GR_beta.tsv"))
```

```{r}
myrhos %>%
  group_by(model, thin) %>%
  summarize(ess.m=mean(ess, na.rm=T),
            ess.sd=sd(ess, na.rm=T)) %>%
  ungroup() %>%
  write_tsv(here::here("tables", "mcmc_convergence", "ESS_rho.tsv"))
```

# MODEL FITS
```{r}
myr2final <- map_dfr(mynames, R2fit)
```

```{r}
p <- myr2final %>% filter(thin==1000) %>%
  mutate(phase=factor(phase, levels=c("sorting", "quasi-equilibrium")),
         model=factor(model, levels=c("full", "no_random_effects", "no_fixed_effects"))) %>%
  ggplot(aes(x=distribution, y=R2, fill=model)) +
  geom_col(position = position_dodge()) +
  scale_fill_carto_d(palette="Vivid") +
  facet_grid(~ phase) +
  theme_bw() +
  theme(axis.text.x=element_text(angle = -90, vjust = 0.5),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())

ggsave(here::here("figs", "model_fits", "R2_page3.svg"), plot=p, device="svg",
                  units="cm", width=27.8, height=10)

p
```

```{r}
myr2final %>%
  ungroup() %>%
  group_by(model, thin, phase, distribution) %>%
  summarize(mean_R2=mean(R2, na.rm=T),
         sd_R2=sd(R2, na.rm=T),
         mean_RMSE=mean(RMSE, na.rm=T),
         sd_RMSE=sd(RMSE, na.rm=T),
         mean_AUC=mean(AUC, na.rm=T),
         sd_AUC=sd(AUC, na.rm=T)) %>%
  write_tsv(here::here("tables", "model_fits", "R2_summary_results.tsv"))
```

# WAIC
```{r}
mywaicfinal <- map_dfr(mynames, WAICfit)
```

```{r}
mywaicfinal %>%
  group_by(phase, distribution, model, thin) %>%
  summarize(min=min(WAIC_full)) %>%
  write_tsv(here::here("tables", "model_fits", "min_waic.tsv"))
```

# 5-FOLD CROSS VALIDATION
```{r}
finalnames <- c("qeq_ma_full_thin_1000_samples_250_chains_4.rds", 
                "qeq_mp_full_thin_1000_samples_250_chains_4.rds",
                "sort_ma_full_thin_1000_samples_250_chains_4.rds",
                "sort_mp_full_thin_1000_samples_250_chains_4.rds")

mycv5final <- map_dfr(finalnames, cv5fit)
```

```{r}
mycv5final %>% 
  filter(R2 > 0) %>%
  group_by(phase, distribution) %>%
  mutate(mean_R2=mean(R2, na.rm=T),
         sd_R2=sd(R2, na.rm=T),
         mean_RMSE=mean(RMSE, na.rm=T),
         sd_RMSE=sd(RMSE, na.rm=T),
         mean_AUC=mean(AUC, na.rm=T),
         sd_AUC=sd(AUC, na.rm=T)) %>%
  write_tsv(here::here("tables", "model_fits", "cv5f_results.tsv"))
```

```{r}
mycv5final %>%
  ungroup() %>%
  filter(R2 > 0) %>%
  group_by(phase, distribution) %>%
  summarize(mean_R2=mean(R2, na.rm=T),
         sd_R2=sd(R2, na.rm=T),
         mean_RMSE=mean(RMSE, na.rm=T),
         sd_RMSE=sd(RMSE, na.rm=T),
         mean_AUC=mean(AUC, na.rm=T),
         sd_AUC=sd(AUC, na.rm=T)) 
```

```{r}
myr2final %>%
  filter(thin==1000) %>%
  group_by(phase, distribution, model) %>%
  summarize(mean_R2=mean(R2, na.rm=T),
         sd_R2=sd(R2, na.rm=T),
         mean_RMSE=mean(RMSE, na.rm=T),
         sd_RMSE=sd(RMSE, na.rm=T),
         mean_AUC=mean(AUC, na.rm=T),
         sd_AUC=sd(AUC, na.rm=T)) 
```

