library(here)

source(here::here("R", "rpkm2tab.R"))
source(here::here("R", "format_raw_data.R"))
source(here::here("R", "correct_bias.R"))
source(here::here("R", "normalize_counts.R"))
source(here::here("R", "gam_ciliate_density.R"))
source(here::here("R", "gam_OD600_density.R"))
source(here::here("R", "gam_nematode_density.R"))
source(here::here("R", "competitive_LV.R"))
source(here::here("R", "fig2.R"))
source(here::here("R", "figS1a.R"))
source(here::here("R", "community_dissimilarity_plot.R"))
source(here::here("R", "community_dissimilarity_regression.R"))
source(here::here("R", "shannon_diversity.R"))
source(here::here("R", "shannon_change_point_regression.R"))
source(here::here("R", "shannon_sort_eq_regression_bayes.R"))
source(here::here("R", "ordination.R"))
source(here::here("R", "fig3.R"))
source(here::here("R", "traits.R"))
source(here::here("R", "JSDM_convergence.R"))
source(here::here("R", "JSDM_inspect.R"))
source(here::here("R", "fig5.R"))
source(here::here("R", "consumer_feeding_stats.R"))